<?php $quote = $this->getQuote() ?>
<div class="page-title">
    <h2><?php echo $this->__('Edit Quote') ?></h2>
</div>
<?= $quote->getName()?>
<form id="quote-form-validate" method="post" action="<?php echo $this->getActionOfForm()?>">
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Quote Information')?></h2>
        <ul class="form-list">
            <li class="fields">
                <div class="customer-name">
                    <div class="field name-name">
                        <label class="required" for="name"><em>*</em><?php echo $this->__('Name')?></label>
                        <div class="input-box">
                            <input type="text" class="input-text required-entry" maxlength="255" title="Name" value="<?php echo $quote->getName()?>" name="name" id="name">
                        </div>
                    </div>
                    <div class="field dscr">
                        <label class="required" for="dscr"><em>*</em><?php echo $this->__('Dscr')?></label>
                        <div class="input-box">
                            <input type="text" class="input-text required-entry" maxlength="255" title="Dscr" value="<?php echo $quote->getDscr()?>" name="dscr" id="dscr">
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </div>

    <div class="buttons-set">
        <p class="required">* <?php echo $this->__('Required Fields')?></p>
        <p class="back-link"><a class="back-link" href="<?php echo $this->getBackUrl() ?>"><small>&laquo;</small>Back</a></p>
        <button class="button" title="Submit" type="submit"><span><span><?php echo $this->__('Submit')?></span></span></button>
    </div>
</form>
<script type="text/javascript">
    var dataForm = new VarienForm('quote-form-validate', true);
</script>